version: '3'

services:
  db:
    image: postgres:12
    container_name: 'postgres'
    env_file: .env
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - 4000:3000
      - 9229:9229
    volumes:
      - .:/app/
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_PORT
